- internal/controller/gateway_controller.go
- internal/controller/httproute_controller.go
- internal/controller/indexer/indexer.go
- internal/manager/controllers.go
- internal/manager/run.go
> chore: indexer does not need to be set for each controller

- .github/workflows/conformance-test.yml
- internal/controller/httproute_controller.go
- internal/provider/adc/adc.go
- test/e2e/gatewayapi/httproute.go
> fix: route/service still exist when deleting the Gateway

- Dockerfile
- Makefile
refs: https://github.com/api7/adc/releases/tag/v0.18.0
> chore: upgrade adc to 0.18.0

- internal/controller/consumer_controller.go
- internal/controller/indexer/indexer.go
- internal/provider/adc/translator/consumer.go
- test/e2e/crds/consumer.go
- test/e2e/scaffold/scaffold.go
```yaml
apiVersion: v1
kind: Secret
metadata:
name: key-auth-secret
data:
key: c2FtcGxlLWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
name: basic-auth-secret
data:
username: c2FtcGxlLXVzZXI=
password: c2FtcGxlLXBhc3N3b3Jk
---
apiVersion: gateway.apisix.io/v1alpha1
kind: Consumer
metadata:
name: consumer-sample
spec:
gatewayRef:
name: api7ee
credentials:
- type: basic-auth
name: basic-auth-sample
secretRef:
name: basic-auth-secret
- type: key-auth
name: key-auth-sample
secretRef:
name: key-auth-secret
- type: key-auth
name: key-auth-sample2
config:
key: sample-key2
```
> feat: support secret for consumer.credential

- internal/provider/adc/adc.go
- test/e2e/gatewayapi/httproute.go
The library "gopkg.in/yaml.v3" cannot serialize StringOrSlice correctly. 
The library "sigs.k8s.io/yaml" can use a custom MarshalJSON method to serialize.
> fix: HTTPRoute vars match

- internal/controller/gateway_controller.go
- test/e2e/crds/consumer.go
> chore: add consumer plugins test

- internal/provider/adc/adc.go
When generating ids for resources in adc.yaml, there is a chance that an id like `8e287857` will be generated, which adc will recognize as a number and cause an error. We can use a json file instead of a yaml file.
```yaml
services:
- hosts:
- httpbin.example
id: 8e287857
...
```
adc lint log
```log
The following errors were found in configuration:
#1 Expected string, received number at service: "ingress-apisix-e2e-tests-default-894183279_httpbin-0006_0", field: "id"
```
> fix: update ADC to use JSON instead of YAML

- config/manager/manager.yaml
- config/samples/config.yaml
- internal/controller/config/config.go
- internal/controller/config/types.go
- internal/manager/run.go
- internal/types/duration.go
- test/e2e/framework/manifests/ingress.yaml
> feat: support config LeaderElection strategy

- internal/controller/httproute_controller.go
- internal/controller/ingress_controller.go
- internal/controller/policies.go
- internal/provider/adc/translator/ingress.go
- internal/provider/adc/translator/policies.go
- test/e2e/crds/backendtrafficpolicy.go
> feat: support backendtrafficpolicy for Ingress

- internal/controller/httproute_controller.go
- internal/controller/httproutepolicy.go
- internal/controller/indexer/indexer.go
- internal/controller/ingress_controller.go
- internal/provider/adc/translator/httproute.go
- internal/provider/adc/translator/ingress.go
- test/e2e/gatewayapi/httproute.go
- test/e2e/ingress/ingress.go
Refactor the HTTPRoutePolicy update function to handle Ingress objects and improve logging. Add functionality to process HTTPRoutePolicies for Ingress in the IngressReconciler. Update tests to include scenarios for HTTPRoutePolicy targeting Ingress.
> feat: Update HTTPRoutePolicy handling for Ingress

- config/samples/config.yaml
- examples/httpbin/ingress.yaml
- internal/controller/config/config.go
- internal/controller/config/types.go
- internal/provider/adc/adc.go
> fix: hanging the adc program can cause the k8s client to exceed its limit

- internal/controller/httproute_controller.go
- internal/controller/ingress_controller.go
- internal/provider/adc/translator/httproute.go
- internal/provider/adc/translator/ingress.go
- test/e2e/gatewayapi/httproute.go
- test/e2e/ingress/ingress.go
support service with ExternalName
```yaml
apiVersion: v1
kind: Service
metadata:
name: httpbin2
spec:
type: ExternalName
externalName: httpbin.org
```
> feat: support proxy external service

- internal/controller/gatewayclass_congroller.go
- test/e2e/gatewayapi/gateway.go
- test/e2e/gatewayapi/gatewayclass.go
- test/e2e/gatewayapi/gatewayproxy.go
- test/e2e/gatewayapi/httproute.go
- test/e2e/scaffold/k8s.go
- test/e2e/scaffold/scaffold.go
Introduce a finalizer to prevent deletion of GatewayClasses still in use by Gateways, and implement corresponding e2e tests to validate the protection mechanism and proper removal flow.
> chore: Add GatewayClass protection and deletion logic

- internal/controller/gateway_controller.go
- internal/controller/indexer/indexer.go
- internal/controller/utils.go
- test/e2e/gatewayapi/gateway.go
chore: Add support for Secret resources in Gateway reconciliation
> chore: Add support for Secret resources in Gateway reconciliation

- .golangci.yml
- internal/controller/consumer_controller.go
- internal/controller/ingress_controller.go
- internal/controller/ingressclass_controller.go
- test/e2e/crds/consumer.go
- test/e2e/gatewayapi/gateway.go
- test/e2e/gatewayapi/gatewayclass.go
- test/e2e/gatewayapi/gatewayproxy.go
- test/e2e/gatewayapi/httproute.go
- test/e2e/ingress/ingress.go
- test/e2e/scaffold/k8s.go
- test/e2e/scaffold/scaffold.go
Introduce comprehensive e2e tests verifying GatewayProxy's ability to reference Secrets, including scenarios for creating, updating, and validating Secrets with admin keys. Update predicate filters to watch for Secret changes and replace `CurrentNamespace()` with `Namespace()` across multiple test files for consistency. Adjust line length configuration in `.golangci.yml` to accommodate the new test cases.
> chore: Add e2e tests for GatewayProxy referencing Secret

- internal/controller/utils.go
- test/conformance/conformance_test.go
fix: 
https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-invalid-nonexistent-backendref.go#L36-L71
> fix: HTTPRouteInvalidNonExistentBackendRef

- api/v1alpha1/backendtrafficpolicy_types.go
- api/v1alpha1/consumer_types.go
- api/v1alpha1/gatewayproxy_types.go
- api/v1alpha1/httproutepolicy_types.go
- api/v1alpha1/pluginconfig_types.go
- config/crd/bases/apisix.apache.org_backendtrafficpolicies.yaml
- config/crd/bases/apisix.apache.org_consumers.yaml
- config/crd/bases/apisix.apache.org_gatewayproxies.yaml
- config/crd/bases/apisix.apache.org_httproutepolicies.yaml
- config/crd/bases/apisix.apache.org_pluginconfigs.yaml
- docs/crd/api.md
Update comments for CRD docs generation.
TODO: valid column
> docs: update CRD docs

- charts/templates/cluster_role.yaml
- internal/controller/gateway_controller.go
- internal/controller/utils.go
- internal/manager/run.go
- test/conformance/conformance_test.go
- test/e2e/framework/manifests/ingress.yaml
This commit introduces functionality to handle the ReferenceGrant resource in the Gateway API. It updates the Gateway controller logic, adds necessary permissions in RBAC manifests, and integrates condition handling for cross-namespace references. Additionally, skipped conformance tests related to ReferenceGrants are reinstated.
> feat: Add support for Gateway API ReferenceGrant resource

- docs/configure.md
- docs/crd/api.md
- docs/template/gv_list.tpl
- docs/template/type_members.tpl
1. Update CRD doc title and description in the template. Initially was planning to mention supported Gateway API and Ingress resources in the same doc; but now these content are separated.
2. Update template with more string substitution to avoid the need of manual editing after generation.
3. Remove unused Addresses section from `configure.md` which is a missed update from https://github.com/api7/api7-ingress-controller/pull/96
> docs: update CRD doc template and remove dated info from configuration file doc

- internal/controller/consumer_controller.go
- internal/controller/gateway_controller.go
- internal/controller/gatewayclass_congroller.go
- internal/controller/httproute_controller.go
- internal/controller/httproutepolicy.go
- internal/controller/ingress_controller.go
- internal/controller/policies.go
- internal/controller/status.go
- internal/controller/status/updater.go
- internal/controller/utils.go
- internal/manager/controllers.go
- internal/manager/run.go
- internal/provider/adc/adc.go
- internal/provider/provider.go
To avoid state updates blocking the normal synchronization of resources in scenarios where a large amount of resources are synchronized.
> refactor(status): aynsc update status

- .github/workflows/apisix-conformance-test.yml.example
- Makefile
- test/conformance/apisix/conformance_test.go
- test/conformance/apisix/suite_test.go
- test/e2e/framework/api7_gateway.go
- test/e2e/scaffold/api7_deployer.go
- test/e2e/scaffold/apisix_deployer.go
- test/e2e/scaffold/deployer.go
- test/e2e/scaffold/scaffold.go
Because the apisix standalone mode has not been integrated yet, the consistency test cannot be passed normally. The yaml in .github has also not been enabled yet.
In order to support the direct invocation of the `DeployDataplane` function in the conformance test, I added a configuration structure `DeployDataplaneOptions` to override the existing configuration.
> feat: support conformance test for apisix

- internal/controller/apisixroute_controller.go
- internal/provider/adc/translator/apisixroute.go
- test/e2e/apisix/route.go
- test/e2e/framework/assertion.go
Support ApisixRoute resolveGranularity.
> feat: support apisixroute resolveGranularity

- api/v2/apisixconsumer_types.go
- api/v2/apisixglobalrule_types.go
- api/v2/apisixpluginconfig_types.go
- api/v2/apisixroute_types.go
- api/v2/apisixtls_types.go
- api/v2/apisixupstream_types.go
- config/crd/bases/apisix.apache.org_apisixconsumers.yaml
- config/crd/bases/apisix.apache.org_apisixglobalrules.yaml
- config/crd/bases/apisix.apache.org_apisixpluginconfigs.yaml
- config/crd/bases/apisix.apache.org_apisixroutes.yaml
- config/crd/bases/apisix.apache.org_apisixtls.yaml
- config/crd/bases/apisix.apache.org_apisixupstreams.yaml
> fix(crd): missing shortname and printcolumn

- internal/provider/adc/config.go
- internal/provider/adc/translator/apisixroute.go
- internal/provider/adc/translator/httproute.go
- internal/provider/adc/translator/ingress.go
> fix: support filter endpoint when translate backend ref. (#2451)

- internal/provider/adc/adc.go
- internal/provider/adc/executor.go
- test/e2e/gatewayapi/gatewayproxy.go
> fix: a failing endpoint shouldn't affect others (#2452)

- test/e2e/crds/v2/route.go
> chore: migrate e2e tests for secretref in apisixroute.plugins

- .github/workflows/apisix-conformance-test.yml
- .github/workflows/conformance-test.yml
- Makefile
- test/conformance/api7ee/conformance_test.go
- test/conformance/api7ee/suite_test.go
- test/conformance/conformance_test.go
- test/conformance/suite_test.go
> (backport) chore: add more conformance-test report for gateway-api (#2557)
